<div id="modal">
      <div id="modal-window">
			<div class="modal-header">
				<button class="modal-dismiss">×</button>
			</div>
			<div id="modal-body">
		        <p>This is a Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt tenetur ratione ipsum eum quod necessitatibus veniam possimus totam dolor temporibus. Delectus, dolorem illo repellendus cupiditate eaque quibusdam sapiente tempora ad.</p>
	        	<hr>
		        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae, sit, magni, possimus numquam quo explicabo quas illo similique harum quisquam minus optio quidem esse perferendis mollitia ipsam soluta sed vero!</p>				
			</div>
      </div>
</div>